### ISSUE TITLE
How can be run it with GPU

### ISSUE THREAD

**Issue by ZIKO94ZIKO** [deepak112/Social-Distancing-AI#1]
Hi Sir , could you please tel me how can be run your project only with GPU using max capacity.?

**Comment by deepak112** [comment]
You can set Backend and Target like this:
 
net.setPreferableBackend(cv2.dnn.DNN_BACKEND_CUDA)
net.setPreferableTarget(cv2.dnn.DNN_TARGET_CUDA)

**Comment by zongoalbert** [comment]
thanks @deepak112 for make this project opensource  ,i have the same problem , when i run the soft it's give me this message Sir : [ WARN:0] global /io/opencv/modules/dnn/src/dnn.cpp (1363) setUpNet DNN module was not built with CUDA backend; switching to CPU
and when i run the camande line : `watch nvidia-smi` to watch nvidia : 
![image](https://user-images.githubusercontent.com/55978810/83761541-faed8800-a665-11ea-9ee3-bb2b56372635.png)

**Comment by zongoalbert** [comment]
like you see python use just  41 MiB

**Comment by ZIKO94ZIKO** [comment]
@zongoalbert  same problem  : `    WARN:0] global /io/opencv/modules/dnn/src/dnn.cpp (1363) setUpNet DNN module was not built with CUDA backend; switching to CPU    `  do you found the solution ?

**Comment by saimj7** [comment]
@ZIKO94ZIKO OpenCV has to be built with CUDA backend in order to fix that error

**Comment by tuanhm11299** [comment]
Do you know how to use OpenCV with CUDA backend on Windows ? Because know I don't have much time to do on linux.
